[autodim]
device = /dev/input/event0
backlight_path = /sys/class/backlight/6-0045/brightness
brightness_max = 31
brightness_low = 5
brightness_min = 0
idle_dim = 10        # seconds until dim
idle_off = 3600      # seconds until off